version: "3.5"
services:
  php_fpm:
    build: .
    container_name: app_php_fpm
    working_dir: /usr/share/nginx/app
    networks:
      - app
    volumes:
      - ./:/usr/share/nginx/app
  scheduler:
    build:
      context: .
      dockerfile: ./docker/scheduler/scheduler.Dockerfile
    container_name: app_scheduler
    working_dir: /usr/share/nginx/app
    depends_on:
      - php_fpm
    networks:
      - app
    volumes:
      - ./:/usr/share/nginx/app
  supervisor:
    build:
      context: .
      dockerfile: ./docker/supervisor/supervisor.Dockerfile
    container_name: app_supervisor
    working_dir: /usr/share/nginx/app
    depends_on:
      - php_fpm
    networks:
      - app
    volumes:
      - ./:/usr/share/nginx/app
  nginx:
    image: nginx:1.15
    container_name: app_nginx
    working_dir: /usr/share/nginx/app
    networks:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:5.7
    container_name: app_mysql
    networks:
      - app
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
      #      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
networks:
  app:
    driver: bridge
